source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "just-the-docs", "~> 0.5.3"
gem "jekyll-github-metadata"
gem "webrick", "~> 1.7"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
gem "jekyll-sitemap"



